spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root

    password: fqh123456

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 9090

files:
  upload:
    path: D:/desktop/git-bishe2/Springboot/files/


spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
